spring:
  profiles:
    active: local
  application:
    name: netty-server
---
spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      connection:
        mode: connection
        size: 20
    listener:
      simple:
       concurrency: 20
       max-concurrency: 40 
---
spring:
  profiles: dev
  rabbitmq:
    host: iot-rabbitmq8
    port: 5672
    username: guest
    password: guest
    cache:
      connection:
        mode: connection
        size: 20
    listener:
      simple:
       concurrency: 20
       max-concurrency: 40